os gen 83: 2026-06-18 13:07

diff --git a/nix/justfile b/nix/justfile
--- a/nix/justfile
+++ b/nix/justfile
@@ -26,7 +26,7 @@ switch *args:
     git add -A
 
     if ! nh "$target" switch {{args}}; then
-      echo -e "\n\e[1;30;41mFailed to switch config!\e[0m\n"
+      echo -e "\n\e[1;30;41mFailed to switch config!\e[0m\n" >&2
       exit 1
     fi
 
